---

- name: Ensure Enpass Repository key exists
  apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://apt.enpass.io/ stable main"
    state: present
    filename: enpass

- name: Ensure Enpass is installed
  apt:
    name: enpass
    state: present
    update_cache: true
