---

- name: Ensure RPM GPG key is present
  rpm_key:
    key: https://yum.enpass.io/RPM-GPG-KEY-enpass-signing-key
    state: present

- name: Ensure Zypper repository file exists
  zypper_repository:
    name: enpass
    description: Enpass password manager repository
    repo: https://yum.enpass.io/stable/x86_64/
    state: present

- name: Ensure Enpass is installed
  zypper:
    name: enpass
    state: present
    update_cache: true
